title: Ebere Ulasi
logo: HeadShot.jpg
description: A data analyst with 3 years of experience using Excel for report automation, SQL for data manipulation and Power BI for visualisation
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
